### ISSUE TITLE
If gzip setting turn on, the loading will be faster. 

### ISSUE THREAD

**Issue by guguji5** [vue-microfrontends/root-config#12]
https://vue.microfrontends.app/rate-doggos loading takes some time, I find the gzip is off.

**Comment by joeldenning** [comment]
Gzip is not off - `gsutil -Z` ensures that they are gzipped before uploaded. My previous commit was in error - I should have verified whether they were gzipped before uploading them.

See the code below:

https://github.com/vue-microfrontends/root-config/blob/05149fe8877313dd7840b874f71ced2490e2db03/.circleci/config.yml#L67

![image](https://user-images.githubusercontent.com/5524384/92008747-c771d680-ed04-11ea-8458-a513d149be36.png)
