### ISSUE TITLE
Is that dynamic inject DOM problems??

### ISSUE THREAD

**Issue by SecretCastle** [vue-microfrontends/root-config#16]
When i reload demo [link](https://vue.microfrontends.app/rate-doggos) in browser tow or three times. I found a problem
![image](https://user-images.githubusercontent.com/12498143/113736784-ff744880-972f-11eb-85aa-9103558d98a1.png)

after two or three times

![image](https://user-images.githubusercontent.com/12498143/113736837-0b600a80-9730-11eb-926e-35cf30e5d16d.png)

dynamic injection of the DOM is disorderly

Is that a bug??

**Comment by joeldenning** [comment]
Good question. This is expected when you're (1) not using single-spa-layout, and (2) don't manually create `<div id="single-spa-application:@vue-mf/navbar"></div>` elements.

When you need to control positioning in the dom, single-spa-layout is recommended. See https://single-spa.js.org/docs/layout-overview
