### ISSUE TITLE
how to control import-map cache?

### ISSUE THREAD

**Issue by guguji5** [vue-microfrontends/root-config#3]

**Comment by guguji5** [comment]
<script type="systemjs-importmap" src="https://storage.googleapis.com/vue.microfrontends.app/importmap.json"></script>

is there any cache strategy for this link ?

**Comment by joeldenning** [comment]
You can control caching of the import map and other files with a [cache-control header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) in the server response. Here are the cache-control headers I usually set:

importmap.json: `Cache-Control: public, must-revalidate, max-age=0`. ([Example](https://storage.googleapis.com/vue.microfrontends.app/importmap.json))
All other javascript files: `Cache-Control: public, max-age=31557600`

^ This means the user always has to redownload the import map (to get the latest deployment), but doesn't have to redownload the javascript files themselves.

Alternatively, you can cache importmap.json for a short period of time, which means it will be faster but deployments won't take effect for a while.

And the most performant alternative is actually to [**inline** the import map](https://github.com/WICG/import-maps#installation) into your HTML file. This means that you must have a dynamic web-server that can modify the HTML response that is sent to the browser. The dynamic web server polls the import map once every 30 seconds, and then injects it into the HTML that is sent to the browser. That way, the browser does not even have to request the import map.

One thing to note: if you are using [import-map-deployer](https://github.com/single-spa/import-map-deployer), it often will automatically set the Cache-Control header for the importmap.json file. See these examples ([1](https://github.com/single-spa/import-map-deployer/blob/master/src/io-methods/google-cloud-storage.js#L36), [2](https://github.com/single-spa/import-map-deployer/blob/master/src/io-methods/s3.js#L74)) which shows that it does so for some of the io-methods.

Let me know if you have other questions!

**Comment by guguji5** [comment]
Got it, thank you for your patient and detailed answer.
